services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5431:5432"
    restart: always
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    command: ["./docker-entrypoint.sh"]
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - BASE_URL=${BASE_URL}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  redis_data: