"""empty message

Revision ID: 917da1a4c4a6
Revises: a80fd227f41d
Create Date: 2022-07-17 14:17:07.728358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917da1a4c4a6'
down_revision = 'a80fd227f41d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('membership_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_member_account_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_account')
    # ### end Alembic commands ###
