"""empty message

Revision ID: cf5877edc3f1
Revises: 273a581e05de
Create Date: 2022-07-08 22:36:28.972165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5877edc3f1'
down_revision = '273a581e05de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
